# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gameoflife.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10gameoflife.proto\x12\nthats_life\"$\n\x04\x43\x65ll\x12\r\n\x05\x61live\x18\x01 \x01(\x08\x12\r\n\x05\x63olor\x18\x02 \x01(\x05\"*\n\x07\x43\x65llRow\x12\x1f\n\x05\x63\x65lls\x18\x01 \x03(\x0b\x32\x10.thats_life.Cell\"H\n\x04Grid\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12!\n\x04rows\x18\x03 \x03(\x0b\x32\x13.thats_life.CellRowB(Z&github.com/HuskyHacks/thats_life/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gameoflife_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&github.com/HuskyHacks/thats_life/pb;pb'
  _globals['_CELL']._serialized_start=32
  _globals['_CELL']._serialized_end=68
  _globals['_CELLROW']._serialized_start=70
  _globals['_CELLROW']._serialized_end=112
  _globals['_GRID']._serialized_start=114
  _globals['_GRID']._serialized_end=186
# @@protoc_insertion_point(module_scope)
